export const mockTableData = [
  {
    item: {
      name: 'CAP Crowns #2713',
      logo: '',
    },
    type: 'Sale',
    price: '5.12 WICP',
    quantity: '1',
    from: 'rgblt...whfy',
    to: 'rgblt...whfy',
    time: '7 hours ago',
    floorDifference: '12.42% above',
    expiration: '2 days',
  },
  {
    item: {
      name: 'CAP Crowns #2713',
      logo: '',
    },
    type: 'Sale',
    price: '5.12 WICP',
    quantity: '1',
    from: 'rgblt...whfy',
    to: 'rgblt...whfy',
    time: '7 hours ago',
    floorDifference: '12.42% above',
    expiration: '2 days',
  },
  {
    item: {
      name: 'CAP Crowns #2713',
      logo: '',
    },
    type: 'Sale',
    price: '5.12 WICP',
    quantity: '1',
    from: 'rgblt...whfy',
    to: 'rgblt...whfy',
    time: '7 hours ago',
    floorDifference: '12.42% above',
    expiration: '2 days',
  },
  {
    item: {
      name: 'CAP Crowns #2713',
      logo: '',
    },
    type: 'Sale',
    price: '5.12 WICP',
    quantity: '1',
    from: 'rgblt...whfy',
    to: 'rgblt...whfy',
    time: '7 hours ago',
    floorDifference: '12.42% above',
    expiration: '2 days',
  },
  {
    item: {
      name: 'CAP Crowns #2713',
      logo: '',
    },
    type: 'Sale',
    price: '5.12 WICP',
    quantity: '1',
    from: 'rgblt...whfy',
    to: 'rgblt...whfy',
    time: '7 hours ago',
    floorDifference: '12.42% above',
    expiration: '2 days',
  },
];
