import miniDfinity from '../../assets/mini-dfinity.svg';
import nftCard from '../../assets/nft-card-image.svg';

export const NftListData = [
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
  },
];
