import miniDfinity from '../../assets/mini-dfinity.svg';
import nftCard from '../../assets/nft-card-image.svg';

export const NftListData = [
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
    id: 1,
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
    id: 2,
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
    id: 3,
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
    id: 4,
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
    id: 5,
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
    id: 6,
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
    id: 7,
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
    id: 8,
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
    id: 9,
  },
  {
    nftImage: nftCard,
    dfintiyIcon: miniDfinity,
    nftName: 'Cap Crowns',
    dfinityValue: '21.12',
    nftId: '2713',
    lastOffer: '4.28',
    id: 10,
  },
];
