name: Release

on:
  push:
    branches:
      - main
      - beta
      - chore/semantic-release-v2

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 📤 Github Release
        run: .scripts/semantic-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.PAT }}

